### ISSUE TITLE
Cannot add protonmail account while using the hydroxide bridge

### ISSUE THREAD

**Issue by garret** [LukeSmithxyz/mutt-wizard#608]
I have a Protonmail account which I access from Thunderbird by connecting to the local imap/smtp server set up by the hydroxide bridge. 

It seems that the hydroxide bridge does not set up a ssl connection and thus, when I try to add my Protonmail address, I always receive a logout unsuccessful error (and the wizards stops). 

Do you know how to solve this issue? 

I noticed that there has been proposed a pull request (https://github.com/LukeSmithxyz/mutt-wizard/pull/486) by @BertalanD to mitigate the issue but cannot understand if it was implemented.

**Comment by LukeSmithxyz** [comment]
Well that PR is sort of obsolete because I rewrote the whole script, but it'd actually be easier to integrate this in now.

I don't know if I really want to add another option, but I guess it would make sense if I have that SSL/TLS is automatically set to off if you give it a typically unencrypted port.

I'm assuming that this Hydroxide Bridge uses the ports 1143 and 1025?

**Comment by garret** [comment]
Yes, it would be really nice to have the SSL/TLS option automatically off in this case. 

The hydroxide bridge uses the following address and ports: 
```
CardDAV server listening on 127.0.0.1:8080
SMTP server listening on 127.0.0.1:1025
IMAP server listening on 127.0.0.1:1143
```

**Comment by LukeSmithxyz** [comment]
Okay. I just changes some things that such that you should be able to give it the port information and automatically assume no TLS.

**Comment by LukeSmithxyz** [comment]
Try that, and also attempt to send mail. More might be necessary for that.

**Comment by garret** [comment]
I don't know if I am doing something wrong but still get the same error (`Log-on not successful`). 
These are my steps: 

1. Deleted `mutt-wizard` folder in my home; 
2. Cloned again `mutt-wizard`; 
3. Reinstalled by giving `sudo make install`; 
4. Run this command: 

```
➜  ~ mw -a myaddress@protonmail.com -p -x "verylongpasswordprovidedbythebridge"
NOTE: Protonmail users must install and configure Protonmail Bridge first for the first sync to work.
msmtp: the server does not support TLS via the STARTTLS command
Give the name you would like to be identified by on the email account:
Generic_name

Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.
➜  ~
```
(I confirm that I do not have any issues with Thunderbird).

**Comment by maheshsundaram** [comment]
@garret What is the "hydroxide" bridge exactly? Just a few minutes ago I was successfully able to run `mw -a myaddress@protonmail.com -p -x "verylongpasswordprovidedbythebridge"` using the latest ProtonMail Bridge (1.5.4). Or at least, the output returned `You should now be able to run `mw -y myaddress@protonmail.com` to begin to download your mail.` I am now running that command (which seems surprisingly slow to download?) 

@LukeSmithxyz Since you are privacy minded and don't seem to use ProtonMail, which mail provider do you use then?

**Comment by garret** [comment]
@maheshsundaram the hydroxide bridge (https://github.com/emersion/hydroxide) is a parallel (unofficial) bridge for protonmail. It aims to work only via cli, to be standard-compliant and fully open-source. Moreover, it is written in go. I prefer it also because it is already in the void linux repo (while that is not the case for the official protonmail bridge). 

In any case, it seems that the implementation of @LukeSmithxyz was not enough to get it working with hydroxide, unless I am doing something wrong (which might be very likely). Maybe @BertalanD could also test this new version of `mw` and see if it works for him. 

I allow myself to reply also to your last question. @LukeSmithxyz made a video some time ago where he showed to have built his own mail server and using a domain he bought. I would assume that is what is using. That is indeed very interesting but yet to complicated for me :)

**Comment by maheshsundaram** [comment]
@garret Thank you for explaining!

**Comment by josh-spatial** [comment]
I'm also getting the ```Log-on not successful.``` error.  I am using the **official** proton bridge.  I'm not sure what I'm doing wrong here.

**Comment by TheMightyV** [comment]
Can confirm, getting `Log-on not successful` with the official protonmail bridge, too.

**Comment by LukeSmithxyz** [comment]
I suspect should be fixed in #635.

**Comment by garret** [comment]
Even after https://github.com/LukeSmithxyz/mutt-wizard/pull/635, I still get the `Log-on not successful` error with the hydroxide bridge, while I can send/receive without any issues with Thunderbird. However, with the new commit I get a slight different error message: 
```
garret@void ~> mw -a myaddress@protonmail.com -p -x "verylongpasswordprovidedbythebridge"
NOTE: Protonmail users must install and configure Protonmail Bridge first for the first sync to work.
msmtp: the server does not support TLS via the STARTTLS command
Log-on not successful.
garret@void ~> 
```
Don't know if I should open a new issue since this now results closed or stay here :/

**Comment by ethancedwards8** [comment]
I also experience this.
