### ISSUE TITLE
Python traceback error

### ISSUE THREAD

**Issue by dankehidayat** [LukeSmithxyz/mutt-wizard#68]
This Error occured when im starting to sync the email `offlineimap -a Personal`
It was worked before on my AntiX Linux, until i moved out to Arch.

```
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 22, in <module>
    oi.run()
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 89, in run
    options, args = self.__parse_cmd_options()
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 265, in __parse_cmd_options
    config.set_if_not_exists('general', 'dry-run', 'False')
  File "/usr/lib/python2.7/site-packages/offlineimap/CustomConfig.py", line 135, in set_if_not_exists
    self.set(section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'
```

**Comment by BurnyBoi** [comment]
Same. I noticed what seems to be happening is that the wizard is not writing anything to ~/.offlineimaprc. It's just completely blank.

**Comment by LukeSmithxyz** [comment]
Hmm, yes it's probably that `offlineimaprc` isn't being generated... I've just cleaned my config and tried to replicate this, but wasn't able to. Some possible things to check out:

+ Do you for some reason not have writing permissions on `~/.offlineimaprc`? Can you create and modify a file there?
+ Does `~/.config/mutt/autoconf/offlineimap_profile` exist? Are you sure you cloned the entire repository in the correct location?

**Comment by BurnyBoi** [comment]
Ohhhh. I didn't clone it right. I manually downloaded the ZIP and ran it from my Downloads folder. I'll do a proper clone and try again. Thanks!

**Comment by LukeSmithxyz** [comment]
Oh okay, good. @BurnyBoi was that your problem too or is it something different?

**Comment by BurnyBoi** [comment]
That was my comment haha. I seem to have hijacked the thread. @dankehidayat, is this the same scenario happening for you?

**Comment by LukeSmithxyz** [comment]
Lol clumsy me.

Yeah anyway, I might just want to produce a standalone script that does everything automatically since people have this problem semi-regularly. I could theoretically nag about people not reading documentation or something, but it's honestly understandable and it would be easier if it was just one whole file.

**Comment by dankehidayat** [comment]
I just did clone the repo on ~/.config/mutt
And run the script `sudo ./mutt-wizard.sh`. As i almost finish the setup, i see something blinking like `can't read directory blablabla..`. And i want to know where is the log file keeped?

**Comment by LukeSmithxyz** [comment]
Oh well that's definitely it then: `autoconf/` doesn't contain personalized info, but the necessary template files and it's needed for the script to run correctly.

The intended way to delete an account is the delete option in the menu. This will get rid of the accounts info in `accounts`, the data in the rc files and your encrypted passwords in `credentials/`. `autoconf/` is not part of that; it is absolutely necessary to add accounts.

If you reclone the repo, do you still have problems?

**Comment by dankehidayat** [comment]
Whoops sorry, the autoconf does exist. (What's wrong with my eyes >. >) I'll try it again.

**Comment by dankehidayat** [comment]
Sorry to say, but no luck for me :disappointed:, Already followed any instruction you given but still..

**Comment by LukeSmithxyz** [comment]
What email site are you using then? Is there any particularly strange characters in your email? You didn't give a multiword name to your account?

What is the error you see this time?

**Comment by dankehidayat** [comment]
![20180714_010842](https://user-images.githubusercontent.com/35223883/42706909-9afb01cc-8702-11e8-9d84-246bc6ee5f2e.png)

**Comment by LukeSmithxyz** [comment]
Okay, so I think I've fixed this problem. If you're still attempting this, get the newest version and try one more time.

**Comment by dankehidayat** [comment]
Okay, gonna do it this night. Hopefully it will worked. :blush:

**Comment by dankehidayat** [comment]
Smh, it's still not worked. I guess it's not the setup fault. I think i need to configure offlineIMAP first.

Gonna close this issue for now. Thanks for your help so far Luke!

**Comment by longestmt** [comment]
> This Error occured when im starting to sync the email `offlineimap -a Personal`
> It was worked before on my AntiX Linux, until i moved out to Arch.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/offlineimap", line 22, in <module>
>     oi.run()
>   File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 89, in run
>     options, args = self.__parse_cmd_options()
>   File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 265, in __parse_cmd_options
>     config.set_if_not_exists('general', 'dry-run', 'False')
>   File "/usr/lib/python2.7/site-packages/offlineimap/CustomConfig.py", line 135, in set_if_not_exists
>     self.set(section, option, value)
>   File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
>     ConfigParser.set(self, section, option, value)
>   File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
>     raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'general'
> ```

I'm getting this exact same error. Was the cause ever discovered?
